# Generated by Django 4.1.5 on 2023-01-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('summary', models.CharField(max_length=80)),
                ('contentRating', models.CharField(max_length=80)),
                ('genre', models.CharField(max_length=80)),
                ('installs', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=80)),
            ],
        ),
    ]
